name: Posts management

on:
  [issues]

jobs:
  close-unauthorized-issues:
    runs-on: ubuntu-latest
    steps:
      - name: close unauthorized issues
        if: github.repository_owner == 'SalHe'
        uses: actions-cool/issues-helper@v2.0.0
        with:
          actions: 'create-comment'
          issue-number: ${{ github.event.issue.number }}
          body: |
            Test condition!
      - run: echo ${{ github.event.issue.user.login }}
