name: Posts management

on:
  issues:
    type: [opened]

jobs:
  close-unauthorized-issues:
    runs-on: ubuntu-latest
    steps:
      - name: close unauthorized issues
        if: github.repository_owner != github.event.issue.user.login
        uses: actions-cool/issues-helper@v2.0.0
        with:
          actions: 'close-issues'
          issue-number: ${{ github.event.issue.number }}
          body: |
            You're not allowed open issue in this repository. Please contact owner to be guaranteed.
